# Descomposición en Valores Singulares (SVD)

## Introducción

Cuando trabajamos en problemas de Machine Learning, muchas veces nos encontramos con conjuntos de datos grandes que contienen además muchas características o feactures. Una forma simple de reducir las dimensiones de estas características es aplicar alguna técnica de Factorización de matrices.

La factorización es una técnica que consiste en la descomposición de una expresión matemática (que puede ser un número, una matriz, un tensor, etc.) en forma de producto. La descomposición en valores singulares, es la base del análisis de componentes principales (PCA), cuyo propósito es derivar un número relativamente pequeño de combinaciones lineales no correlacionadas (componentes principales) de un conjunto de variables aleatorias de media cero mientras que conserva la mayor cantidad de información de las variables originales como sea posible. 

Los principales objetivos del PCA son:

- Reducción de dimensionalidad
- Determinación de combinaciones lineales de variables
- Selección de características o features más útiles
- Visualización de datos multidimensionales
- Identificación de las variables subyacentes
- Identificación grupos de objetos o de valores atípicos

La descomposición en valores singulares para una matriz de datos A está dada por la expresión:

$$A = U \Sigma V^T$$

donde: 

- U es una matriz mxm cuyas columnas corresponden a los vectores singulares izquierdos de A
- $\Sigma$ es una matriz mxn diagonal cuyas entradas corresponden a los valores singulares de A.
- $V^T$ es la traspuesta de la matriz nxn T cuyas columnas corresponden a los vectores singulares derechos de A.

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

In [2]:
#Lectura de datos
datos= pd.read_csv('data/filtered1_dataset.csv', sep=',', index_col="patient_id")
datos.head()

,treatment,birth_date,start_date,start_night,end_night,gender,height,weight,age,smoking,...,beer,wine,alcohol,strong_licor,sistolic,diastolic,heart_rate,pulse_pressure,cardiac_index,systemic_vascular_resistance
patient_id,,,,,,,,,,,,,,,,,,,,,
30,True,1983-12-25 00:00:00,2017-11-01 07:02:00,2017-10-27 04:30:00,2017-10-27 06:30:00,m,1.78,102.0,33.854327,0,...,0,0,1,0,120.457143,79.957143,72.685714,41.0,2.3,1158.0
31,False,1946-10-09 00:00:00,2017-11-01 08:40:00,2017-11-02 02:00:00,2017-11-02 04:00:00,m,1.67,82.4,71.064644,0,...,0,0,1,0,143.405405,91.067568,65.500000,52.0,2.8,1417.0
32,True,1960-02-14 00:00:00,2017-11-01 09:57:00,2017-11-02 03:00:00,2017-11-02 05:00:00,m,1.70,93.2,57.715030,0,...,0,1,1,0,122.557143,90.257143,80.628571,32.0,3.0,1319.0
33,False,1974-03-11 00:00:00,2017-11-01 10:17:00,2017-11-02 03:20:00,2017-11-02 05:20:00,f,1.60,61.3,43.645252,0,...,0,0,0,0,145.893939,93.863636,79.787879,52.0,4.2,1353.0
34,True,1996-06-26 00:00:00,2017-11-01 10:36:00,2017-11-02 04:30:00,2017-11-02 06:30:00,m,1.73,72.3,21.350970,0,...,1,0,1,0,130.376812,82.739130,77.913043,48.0,3.2,1172.0

In [3]:
# Extraemos la variable respuesta "treatment"
y = pd.DataFrame(datos["treatment"])
y.head()

            treatment
patient_id
30               True
31              False
32               True
33              False
34               True

In [4]:
np.shape(y)

(17644, 1)

In [5]:
# Extraer las variables independientes 
X = datos.iloc[:,6:]
X.head()

,height,weight,age,smoking,excercise_frecuency,beer,wine,alcohol,strong_licor,sistolic,diastolic,heart_rate,pulse_pressure,cardiac_index,systemic_vascular_resistance
patient_id,,,,,,,,,,,,,,,
30,1.78,102.0,33.854327,0,5,0,0,1,0,120.457143,79.957143,72.685714,41.0,2.3,1158.0
31,1.67,82.4,71.064644,0,2,0,0,1,0,143.405405,91.067568,65.500000,52.0,2.8,1417.0
32,1.70,93.2,57.715030,0,1,0,1,1,0,122.557143,90.257143,80.628571,32.0,3.0,1319.0
33,1.60,61.3,43.645252,0,1,0,0,0,0,145.893939,93.863636,79.787879,52.0,4.2,1353.0
34,1.73,72.3,21.350970,0,1,1,0,1,0,130.376812,82.739130,77.913043,48.0,3.2,1172.0

In [6]:
np.shape(X)

(17644, 15)

In [7]:
# Singular-value decomposition, usando la función svd()
from scipy.linalg import svd
U, s, VT = svd(X)
print('Matriz U')
print(U)
print('Matriz Sigma')
print(s)
print('Matriz VT')
print(VT)

Matriz U
[[-6.83990442e-03  1.56316422e-02 -7.54467816e-03 ... -8.15496981e-03
  -7.78575566e-03 -7.49807910e-03]
 [-8.35041140e-03 -4.88857912e-03 -6.85395113e-03 ... -4.95743539e-03
  -1.19907261e-02  1.36832328e-02]
 [-7.77517814e-03  4.38947180e-03 -3.67085624e-03 ...  4.39324390e-03
   1.22244486e-04  1.09596662e-02]
 ...
 [-7.42218321e-03  7.37269003e-03 -2.00576175e-03 ...  9.99739143e-01
  -9.76020968e-05 -1.68803387e-04]
 [-7.38181640e-03  8.06593980e-03 -5.22870266e-03 ... -9.43174062e-05
   9.99377078e-01  3.85819628e-05]
 [-6.51868569e-03  5.21711467e-04  9.11175492e-03 ... -1.69960523e-04
   3.61725557e-05  9.99094508e-01]]
Matriz Sigma
[1.71679061e+05 2.29152786e+03 1.62692676e+03 1.41582673e+03
 1.12319150e+03 5.19575427e+02 1.88948312e+02 7.42906011e+01
 4.10785569e+01 3.40019261e+01 3.14321436e+01 3.05116067e+01
 1.93002900e+01 1.81413223e+01 6.70714733e+00]
Matriz VT
[[-1.27026666e-03 -5.72430432e-02 -4.15451238e-02 -4.48346188e-05
  -2.06485217e-03 -7.15043629e-05 -7.53127580e-05 -2.26669475e-04
  -1.31529329e-04 -9.98293631e-02 -6.39414106e-02 -5.73460218e-02
  -3.58844682e-02 -2.45077643e-03 -9.88106576e-01]
 [ 5.26238789e-03  6.72916206e-01 -5.83761612e-01  6.39084529e-04
  -2.12769679e-05  3.31242819e-03 -2.47660084e-04  4.72365096e-03
   3.64428143e-03  2.41718807e-01  2.59247418e-01  2.74523933e-01
  -1.71987691e-02 -1.06915072e-03 -7.09499451e-02]
 [-2.97574510e-03 -6.76291989e-01 -6.14143565e-01  4.85516682e-04
  -2.29026563e-03  9.88495318e-04  4.19883207e-04 -1.73954081e-03
  -2.63487957e-03 -6.31035820e-02  2.02480602e-01  2.14021135e-01
  -2.66046552e-01  2.81064281e-02  5.54538347e-02]
 [-2.92771627e-03 -2.17122782e-01 -1.92185749e-01  5.93305538e-04
   4.60793690e-03  8.05657745e-04 -4.62317228e-04  3.75568775e-04
   2.09275929e-04  6.21013255e-01  1.05286102e-01 -5.00277758e-01
   5.17020636e-01 -8.28015185e-03 -3.86234515e-02]
 [ 4.55430598e-04  1.86302848e-01 -2.09383597e-01 -6.57398019e-04
   2.51791554e-02  2.22113049e-03  1.99420037e-03  6.97057330e-03
   4.59523396e-03 -2.90916156e-01  1.41431878e-01 -7.86353567e-01
  -4.34887647e-01 -4.75731220e-02  7.97428803e-02]
 [ 1.15211221e-02  6.09585838e-02 -4.45818043e-01 -1.92261989e-03
   4.88007737e-02  9.18482925e-04 -2.62061609e-03 -8.94801146e-03
  -7.66757687e-03 -3.49851999e-01 -7.21934270e-01 -6.17694774e-02
   3.73096143e-01 -2.54870329e-02  8.72611359e-02]
 [-1.26021814e-02  8.97583888e-03 -2.65377688e-02  3.87340498e-03
  -9.97505719e-01 -7.95892753e-03 -1.69326371e-02 -3.29687597e-02
  -1.45378059e-02 -2.01636341e-02 -3.25767788e-02 -2.62496661e-02
   8.93780074e-03  8.60945005e-03  8.03039912e-03]
 [ 1.54722603e-02 -6.96593412e-03 -1.69404295e-03  6.58986191e-02
  -3.92226536e-02  2.61796275e-01  2.71584905e-01  7.65229844e-01
   5.15138785e-01 -4.81249323e-03 -1.06634154e-02  5.09283885e-03
   8.52141625e-03 -1.87527499e-02  8.67829221e-04]
 [ 5.58660953e-03  1.78793083e-03  1.94260651e-03 -5.22065229e-02
  -7.85417048e-03  3.69432763e-01  6.28126662e-01  1.08163645e-01
  -6.73839769e-01 -9.45807922e-03  1.27179410e-02 -2.10029966e-04
   1.02577683e-02 -5.90829790e-03 -3.96495276e-04]
 [ 1.74552235e-02 -1.93221618e-03  3.88874990e-03  2.67361948e-04
   4.45788005e-03  8.18756514e-01 -5.66343758e-01 -2.37626144e-02
  -8.31832448e-02  1.35159051e-02 -1.09443214e-02  1.18090209e-03
  -1.42966523e-02 -2.35928097e-02 -2.31014734e-04]
 [-7.26207510e-04 -9.59021681e-05 -3.81049966e-05 -2.78643373e-02
   1.53933846e-03 -7.97585538e-03  2.84994913e-02 -5.54945425e-04
  -3.52037632e-03  5.77713100e-01 -5.77347727e-01  8.54834616e-04
  -5.75541239e-01 -9.17443072e-04 -1.46750949e-04]
 [ 1.46216331e-03  9.21291280e-04  6.15706069e-05  9.95378179e-01
   6.14419842e-03 -1.10731171e-02 -7.66099022e-04 -2.17344058e-02
  -8.82700228e-02  1.47802607e-02 -1.65609458e-02 -1.12004917e-03
  -1.60626700e-02  6.50836481e-03  1.12361797e-04]
 [-6.25567753e-02  3.30881350e-03 -4.30707607e-04  3.56931368e-02
   4.67108028e-03  3.52566677e-01  4.54542026e-01 -6.26194044e-01
   5.12530950e-01 -5.91463861e-03  3.05632883e-03 -4.77284194e-03
   4.29264700e-03  9.47388916e-02  1.96636620e-04]
 [ 5.77709805e-01 -2.65640146e-02  8.15188509e-03  7.50508123e-03
  -1.53870879e-02  6.44060724e-03  5.67940931e-02 -9.12375924e-02
   5.33442707e-02  1.42735810e-02  1.84405880e-02  3.83806058e-02
  -1.47434143e-03 -8.05434558e-01 -2.31727853e-03]
 [ 8.13278297e-01  1.07556425e-02  9.06516761e-04 -5.21363597e-03
  -4.17292487e-03 -2.68680337e-03 -2.90488340e-03  1.46744598e-03
  -1.85194936e-03 -5.14715326e-03 -4.01383385e-03 -2.97237979e-02
  -2.99364126e-03  5.80913699e-01 -5.24731728e-04]]

In [8]:
U.shape, VT.shape, s.shape

((17644, 17644), (15, 15), (15,))

## Reconstruir matriz desde SVD

La matriz original se puede reconstruir a partir de los elementos $U$, $\Sigma$ y $V ^ T$. Pero los elementos $U$, $\Sigma$ y $V ^ T$ devueltos desde la función svd() no se pueden multiplicar directamente.

El vector s debe convertirse en una matriz diagonal utilizando la función diag(). Por defecto, esta función creará una matriz cuadrada que es n x n, en relación con nuestra matriz original. Esto causa un problema ya que el tamaño de las matrices no se ajusta a las reglas de multiplicación de matrices, donde el número de columnas en una matriz debe coincidir con el número de filas en la matriz posterior.

Después de crear la matriz diagonal $\Sigma$ cuadrada, los tamaños de las matrices son relativos a la matriz original m x n que estamos descomponiendo, de la siguiente manera:

In [9]:
# Reconstruir la matriz de datos
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

# Creamos la matriz Sigma mxn 
S = zeros((X.shape[0], X.shape[1]))
S[:X.shape[1], :X.shape[1]] = diag(s)
datos1 = U.dot(S.dot(VT))
print('Matriz de datos reconstruida')
pd.DataFrame(datos1.round(2), columns=X.columns, index=X.index)

Matriz de datos reconstruida

,height,weight,age,smoking,excercise_frecuency,beer,wine,alcohol,strong_licor,sistolic,diastolic,heart_rate,pulse_pressure,cardiac_index,systemic_vascular_resistance
patient_id,,,,,,,,,,,,,,,
30,1.78,102.0,33.85,0.0,5.0,0.0,0.0,1.0,0.0,120.46,79.96,72.69,41.0,2.3,1158.0
31,1.67,82.4,71.06,-0.0,2.0,0.0,0.0,1.0,0.0,143.41,91.07,65.50,52.0,2.8,1417.0
32,1.70,93.2,57.72,-0.0,1.0,0.0,1.0,1.0,0.0,122.56,90.26,80.63,32.0,3.0,1319.0
33,1.60,61.3,43.65,0.0,1.0,0.0,-0.0,0.0,0.0,145.89,93.86,79.79,52.0,4.2,1353.0
34,1.73,72.3,21.35,0.0,1.0,1.0,-0.0,1.0,0.0,130.38,82.74,77.91,48.0,3.2,1172.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20167,1.58,92.0,53.24,-0.0,1.0,0.0,-0.0,0.0,0.0,138.57,84.67,81.30,54.0,3.3,1244.0
20169,1.70,73.0,36.61,0.0,1.0,0.0,-0.0,0.0,0.0,116.90,78.85,73.51,38.0,2.8,1172.0
20170,1.78,88.0,45.93,0.0,3.0,0.0,-0.0,0.0,0.0,128.33,86.01,77.01,42.0,2.9,1258.0
20171,1.67,93.0,47.70,-0.0,2.0,0.0,-0.0,1.0,1.0,126.97,85.51,74.09,41.0,2.7,1251.0
20175,1.70,57.0,38.56,0.0,1.0,0.0,-0.0,0.0,0.0,102.99,69.70,78.28,33.0,3.1,1107.0

Se observa que la matriz de datos se puede descomponer como el producto de las matrices  $U$, $\Sigma$ y $V^T$. Esto indica que cualquier transformación podría expresarse como una secuencia de rotación $V^T$, escala $\Sigma$ y una nueva rotación $U$, es decir, cada valor es un factor de escala a lo largo de un eje particular.

En el cado de la Clasificación y/o regresión estos valores indican el impacto de un eje particular en el resultado general.